### ISSUE TITLE
Aurelia-KendoUI app does not work after updating to the two days old Aurelia release

### ISSUE THREAD

**Issue by adriatic** [aurelia-widgets/aurelia-kendoui#24]
I updated my local copy of [Aurelia-KendoUI](https://github.com/aurelia-widgets/aurelia-kendoui) application with this [latest](http://blog.durandal.io/2015/10/13/aurelia-mid-october-2015-releases-performance-and-portable-javascript/) version of Aurelia and am getting these errors:
```
'window.webkitStorageInfo' is deprecated. Please use 'navigator.webkitTemporaryStorage' or 'navigator.webkitPersistentStorage' instead.
system.src.js:4559 'webkitIndexedDB' is deprecated. Please use 'indexedDB' instead.
aurelia-logging-console.js:38 DEBUG [aurelia] Loading plugin http://localhost:9000/jspm_packages/github/aurelia/templating-binding@0.16.0.
aurelia-logging-console.js:38 DEBUG [aurelia] Configured plugin http://localhost:9000/jspm_packages/github/aurelia/templating-binding@0.16.0.
aurelia-logging-console.js:38 DEBUG [aurelia] Loading plugin http://localhost:9000/jspm_packages/github/aurelia/templating-resources@0.16.0.
aurelia-logging-console.js:38 DEBUG [aurelia] Configured plugin http://localhost:9000/jspm_packages/github/aurelia/templating-resources@0.16.0.
aurelia-logging-console.js:38 DEBUG [aurelia] Loading plugin http://localhost:9000/jspm_packages/github/aurelia/history-browser@0.9.0.
aurelia-logging-console.js:38 DEBUG [aurelia] Configured plugin http://localhost:9000/jspm_packages/github/aurelia/history-browser@0.9.0.
aurelia-logging-console.js:38 DEBUG [aurelia] Loading plugin http://localhost:9000/jspm_packages/github/aurelia/templating-router@0.17.0.
aurelia-logging-console.js:38 DEBUG [aurelia] Configured plugin http://localhost:9000/jspm_packages/github/aurelia/templating-router@0.17.0.
aurelia-logging-console.js:38 DEBUG [aurelia] Loading plugin http://localhost:9000/jspm_packages/github/aurelia/event-aggregator@0.9.0.
aurelia-logging-console.js:38 DEBUG [aurelia] Configured plugin http://localhost:9000/jspm_packages/github/aurelia/event-aggregator@0.9.0.
aurelia-logging-console.js:46 INFO [aurelia] Aurelia Started
aurelia-logging-console.js:38 DEBUG [templating] importing resources for http://localhost:9000/dist/app.html ["nav-bar.html", "bootstrap/css/bootstrap.css"]
aurelia-logging-console.js:38 DEBUG [templating] importing resources for http://localhost:9000/dist/nav-bar.html []
aurelia-logging-console.js:38 DEBUG [templating] importing resources for http://localhost:9000/dist/welcome.html []
aurelia-logging-console.js:38 DEBUG [templating] importing resources for http://localhost:9000/dist/autocomplete.html ["http://localhost:9000/dist/components/auto-complete"]
aurelia-logging-console.js:38 DEBUG [templating] importing resources for http://localhost:9000/dist/components/auto-complete.js []
shim.min.js:1444 Unhandled promise rejection TypeError: $(...).kendoAutoComplete is not a function(…)(anonymous function) @ shim.min.js:1444b.exports @ shim.min.js:453b.(anonymous function) @ shim.min.js:1625f @ shim.min.js:1596q @ shim.min.js:1600
aurelia-logging-console.js:38 DEBUG [templating] importing resources for http://localhost:9000/dist/toolbar.html []
shim.min.js:1444 Unhandled promise rejection TypeError: Cannot read property 'destroy' of undefined(…)(anonymous function) @ shim.min.js:1444b.exports @ shim.min.js:453b.(anonymous function) @ shim.min.js:1625f @ shim.min.js:1596q @ shim.min.js:1600
shim.min.js:1444 Unhandled promise rejection TypeError: Cannot read property 'destroy' of undefined(…)(anonymous function) @ shim.min.js:1444b.exports @ shim.min.js:453b.(anonymous function) @ shim.min.js:1625f @ shim.min.js:1596q @ shim.min.js:1600
aurelia-logging-console.js:38 DEBUG [templating] importing resources for http://localhost:9000/dist/chart.html ["http://localhost:9000/dist/components/chart"]
aurelia-logging-console.js:38 DEBUG [templating] importing resources for http://localhost:9000/dist/components/chart.js []
aurelia-logging-console.js:62 ERROR [aurelia-kendoui] kendo.dataviz.ui.Chart is not defined. Ensure that the professional version of Kendo UI is installed.error @ aurelia-logging-console.js:62log @ aurelia-logging.js:36error @ aurelia-logging.js:69Chart @ chart.js:14invoke @ aurelia-dependency-injection.js:295invoke @ aurelia-dependency-injection.js:511get @ aurelia-templating.js:1425get @ aurelia-dependency-injection.js:446elementContainerGet @ aurelia-templating.js:1469create @ aurelia-templating.js:3294applyInstructions @ aurelia-templating.js:1548create @ aurelia-templating.js:1779create @ aurelia-templating.js:3306(anonymous function) @ router-view.js:44f @ shim.min.js:1415(anonymous function) @ shim.min.js:1423b.exports @ shim.min.js:453b.(anonymous function) @ shim.min.js:1625f @ shim.min.js:1596q @ shim.min.js:1600
aurelia-logging-console.js:38 DEBUG [templating] importing resources for http://localhost:9000/dist/grid.html ["http://localhost:9000/dist/components/grid"]
aurelia-logging-console.js:38 DEBUG [templating] importing resources for http://localhost:9000/dist/components/grid.js []
aurelia-logging-console.js:62 ERROR [aurelia-kendoui] kendo.ui.Grid is not defined. Ensure that the professional version of Kendo UI is installed.error @ aurelia-logging-console.js:62log @ aurelia-logging.js:36error @ aurelia-logging.js:69Grid @ grid.js:14invoke @ aurelia-dependency-injection.js:295invoke @ aurelia-dependency-injection.js:511get @ aurelia-templating.js:1425get @ aurelia-dependency-injection.js:446elementContainerGet @ aurelia-templating.js:1469create @ aurelia-templating.js:3294applyInstructions @ aurelia-templating.js:1548create @ aurelia-templating.js:1779create @ aurelia-templating.js:3306(anonymous function) @ router-view.js:44f @ shim.min.js:1415(anonymous function) @ shim.min.js:1423b.exports @ shim.min.js:453b.(anonymous function) @ shim.min.js:1625f @ shim.min.js:1596q @ shim.min.js:1600
aurelia-logging-console.js:62 ERROR [app-router] Error: Error invoking TreeViewPage. Check the inner error for details.
------------------------------------------------
inner error: TypeError: kendo.data.HierarchicalDataSource is not a function
    at new TreeViewPage (http://localhost:9000/dist/treeview.js:14:25)
    at Object.invoke (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.11.0/aurelia-dependency-injection.js:295:14)
    at Container.invoke (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.11.0/aurelia-dependency-injection.js:511:31)
    at StrategyResolver.get (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.11.0/aurelia-dependency-injection.js:155:37)
    at Container.get (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.11.0/aurelia-dependency-injection.js:446:23)
    at http://localhost:9000/jspm_packages/github/aurelia/templating@0.16.0/aurelia-templating.js:3627:75
    at f (http://localhost:9000/jspm_packages/npm/core-js@0.9.18/client/shim.min.js:1415:56)
    at http://localhost:9000/jspm_packages/npm/core-js@0.9.18/client/shim.min.js:1423:13
    at b.exports (http://localhost:9000/jspm_packages/npm/core-js@0.9.18/client/shim.min.js:453:24)
    at b.(anonymous function) (http://localhost:9000/jspm_packages/npm/core-js@0.9.18/client/shim.min.js:1625:11)
    at new TreeViewPage (http://localhost:9000/dist/treeview.js:14:25)
    at Object.invoke (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.11.0/aurelia-dependency-injection.js:295:14)
    at Container.invoke (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.11.0/aurelia-dependency-injection.js:511:31)
    at StrategyResolver.get (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.11.0/aurelia-dependency-injection.js:155:37)
    at Container.get (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.11.0/aurelia-dependency-injection.js:446:23)
    at http://localhost:9000/jspm_packages/github/aurelia/templating@0.16.0/aurelia-templating.js:3627:75
    at f (http://localhost:9000/jspm_packages/npm/core-js@0.9.18/client/shim.min.js:1415:56)
    at http://localhost:9000/jspm_packages/npm/core-js@0.9.18/client/shim.min.js:1423:13
    at b.exports (http://localhost:9000/jspm_packages/npm/core-js@0.9.18/client/shim.min.js:453:24)
    at b.(anonymous function) (http://localhost:9000/jspm_packages/npm/core-js@0.9.18/client/shim.min.js:1625:11)
    at new AggregateError (http://localhost:9000/jspm_packages/github/aurelia/pal@0.2.0/aurelia-pal.js:20:13)
    at Container.invoke (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.11.0/aurelia-dependency-injection.js:513:15)
    at StrategyResolver.get (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.11.0/aurelia-dependency-injection.js:155:37)
    at Container.get (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.11.0/aurelia-dependency-injection.js:446:23)
    at http://localhost:9000/jspm_packages/github/aurelia/templating@0.16.0/aurelia-templating.js:3627:75
    at f (http://localhost:9000/jspm_packages/npm/core-js@0.9.18/client/shim.min.js:1415:56)
    at http://localhost:9000/jspm_packages/npm/core-js@0.9.18/client/shim.min.js:1423:13
    at b.exports (http://localhost:9000/jspm_packages/npm/core-js@0.9.18/client/shim.min.js:453:24)
    at b.(anonymous function) (http://localhost:9000/jspm_packages/npm/core-js@0.9.18/client/shim.min.js:1625:11)
    at Number.f (http://localhost:9000/jspm_packages/npm/core-js@0.9.18/client/shim.min.js:1596:24)error @ aurelia-logging-console.js:62log @ aurelia-logging.js:36error @ aurelia-logging.js:69processResult @ aurelia-router.js:1682(anonymous function) @ aurelia-router.js:1575f @ shim.min.js:1415(anonymous function) @ shim.min.js:1423b.exports @ shim.min.js:453b.(anonymous function) @ shim.min.js:1625f @ shim.min.js:1596q @ shim.min.js:1600
```

Please verify and let me know what broke the current app.

**Comment by jedd-ahyoung** [comment]
This is not an Aurelia error - it's a code error caused by the Treeview component not finding the Kendo Hierarchal datasource. That error is most likely caused by the kendo javascript source file being in the wrong directory. Try placing the kendo.all.js file into the `vendor` directory when you pull the project. Alternatively, if your file is named differently (kendo.all.min.js, perhaps) try renaming the file.
